### ISSUE TITLE
PrettierでFormatをかけるタイミング

### ISSUE THREAD

**Issue by uzimaru0000** [yousan/my-helloworld#6]
開発メンバ各自がエディタからPrettierでFormatをかけてくれるプラグインを入れるのは統一性がない、個々人の負担になると思うので `git commit` したタイミングでFormatおよびeslintの構文チェックを入れたいです。

**Comment by yousan** [comment]
Gooooood!

**Comment by yousan** [comment]
検討してもらってありがとうございます！
Gitのプリコミットフックですね、リポジトリ側に入るとかっこよさそう、と思いました！

**Comment by uzimaru0000** [comment]
commitするファイルに `.js` がついているものはあるときは `eslint --fix` をかけるようにしました！
lintがエラーを出すとコミットできない様になってるのですが、それでいいですかね？

**Comment by yousan** [comment]
はい！バッチリです！
